name: medica
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  camera: ^0.10.0+4
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  flutter:
    sdk: flutter
  flutter_emoji: ^2.4.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  heroicons: ^0.9.0
  hexcolor: ^3.0.1
  provider: ^6.1.1
  syncfusion_flutter_calendar: ^23.1.43
  table_calendar: ^3.0.8
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
    - assets/graphics/
