// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWaPs9mwsaJFM5MTReaPVu0eiPq5giSdU',
    appId: '1:731472966238:web:44c32983610b4c15ce7acf',
    messagingSenderId: '731472966238',
    projectId: 'medica-mini-project',
    authDomain: 'medica-mini-project.firebaseapp.com',
    storageBucket: 'medica-mini-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbY9oBmf0qXizxoG1UdJOoImm81CzWs_4',
    appId: '1:731472966238:android:21836bd0e66c6d0ece7acf',
    messagingSenderId: '731472966238',
    projectId: 'medica-mini-project',
    storageBucket: 'medica-mini-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTfBTIhW9YX0HH0gLKCBCLAnw7oFLLYJY',
    appId: '1:731472966238:ios:52ac8343a13f22a5ce7acf',
    messagingSenderId: '731472966238',
    projectId: 'medica-mini-project',
    storageBucket: 'medica-mini-project.appspot.com',
    iosBundleId: 'com.example.medica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTfBTIhW9YX0HH0gLKCBCLAnw7oFLLYJY',
    appId: '1:731472966238:ios:8a67ced0f50f2095ce7acf',
    messagingSenderId: '731472966238',
    projectId: 'medica-mini-project',
    storageBucket: 'medica-mini-project.appspot.com',
    iosBundleId: 'com.example.medica.RunnerTests',
  );
}
